### ISSUE TITLE
On switching off internet, chat messages are shown as sent

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/ARD#175]
Steps to reproduce,

Disconnect internet,
Send message..
it often shows a sent tick mark

**Comment by Rushi98** [comment]
That is because we're not actually checking whether data reached firebase server. One way to implement this would be to add some sort of acknowledgement when data reaches server. This can be done via
1. A dedicated always online device listening to data change and responding to it _or_
2. _(I don't know how)_ Google Cloud functions https://firebase.google.com/docs/functions/database-events

**Comment by kukreja-vikramaditya** [comment]
I have a listener to check this in the Messaging Service returned by the method named `getSentMsgStatusVEL` .. My guess is that offline capabilities may be causing this behaviour?

**Comment by kukreja-vikramaditya** [comment]
Fixed using cloud functions
